spring:
  datasource:
    url: portal-cursos-db.con8uco4y18y.us-east-1.rds.amazonaws.com
    username: root
    password: password_key
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # valida contra tablas ya creadas
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

app:
  jwt:
    secret: this_is_a_demo_secret_key_that_is_long_enough_123456
    expiration-ms: 86400000 # 1 día

aws:
  accessKeyId: access-key
  secretAccessKey: secret-key
  region: us-east-1

server:
  port: 8081
